/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface Election extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): Election;
  clone(): Election;
  methods: {
    candidates(arg0: number | string | BN): NonPayableTransactionObject<{
      id: string;
      name: string;
      voteCount: string;
      0: string;
      1: string;
      2: string;
    }>;

    candidatesCount(): NonPayableTransactionObject<string>;

    voters(arg0: string): NonPayableTransactionObject<boolean>;

    vote(_candidateId: number | string | BN): NonPayableTransactionObject<void>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
